# Project Title:
## T_20 World Cup Analysis

# Role
### Data Analyst
Responsible for 
- data cleaning, 
- exploration, 
- statistical analysis, 
- visualization, 
- insight generation

# Tools & Technologies
1) Python (Pandas, NumPy, Matplotlib, Seaborn, Plotly)
2) Jupyter Notebook / VS Code
3) MySQL (for querying structured data)
4) Excel (for basic dashboarding if needed)
5) Power BI or Tableau (optional, for visualization dashboard)

# Step 1: Data Collection / Import

In [2]:
# Import pandas,Numpy,Seaborn,Matplotlib liabrary
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# Read file in csv,excel,json,text and they define python format read data
df=pd.read_excel(r"c:\Users\ADMIN\Downloads\icc_dataset (1).xlsx")

In [5]:
df_new=df

In [7]:
New=df_new.to_csv("new.csv")

In [4]:
# Data frames stores data 
df

,Tournament,Year,Venue,Winner,Runner-up,Semi-Finalists,Match_Winner_Final,Player_of_Tournament
0,ODI World Cup,1975,England,West Indies,Australia,"WI, AUS, NZ, ENG",Clive Lloyd,-
1,ODI World Cup,1979,England,West Indies,England,"WI, ENG, PAK, NZ",Viv Richards,-
2,ODI World Cup,1983,England,India,West Indies,"IND, WI, PAK, ENG",M. Amarnath,-
3,ODI World Cup,1987,India/PAK,Australia,England,"AUS, ENG, IND, PAK",David Boon,-
4,ODI World Cup,1992,AUS/NZ,Pakistan,England,"PAK, ENG, NZ, SA",Wasim Akram,Martin Crowe
5,ODI World Cup,1996,Asia,Sri Lanka,Australia,"SL, AUS, IND, WI",A. de Silva,Sanath Jayasuriya
6,ODI World Cup,1999,England,Australia,Pakistan,"AUS, PAK, SA, NZ",Shane Warne,Lance Klusener
7,ODI World Cup,2003,South Africa,Australia,India,"AUS, IND, KEN, SL",Ricky Ponting,Sachin Tendulkar
8,ODI World Cup,2007,West Indies,Australia,Sri Lanka,"AUS, SL, NZ, SA",Adam Gilchrist,Glenn McGrath
9,ODI World Cup,2011,Asia,India,Sri Lanka,"IND, SL, PAK, NZ",MS Dhoni,Yuvraj Singh
10,ODI World Cup,2015,AUS/NZ,Australia,New Zealand,"AUS, NZ, IND, SA",James Faulkner,Mitchell Starc
11,ODI World Cup,2019,UK,England,New Zealand,"ENG, NZ, IND, AUS",Ben Stokes,Kane Williamson
12,ODI World Cup,2023,India,Australia,India,"AUS, IND, NZ, SA",Travis Head,Virat Kohli
13,T20 World Cup,2007,South Africa,India,Pakistan,"IND, PAK, AUS, NZ",Irfan Pathan,Shahid Afridi
14,T20 World Cup,2009,England,Pakistan,Sri Lanka,"PAK, SL, SA, WI",Shahid Afridi,T. Dilshan
15,T20 World Cup,2010,West Indies,England,Australia,"ENG, AUS, SL, PAK",C. Kieswetter,K. Pietersen
16,T20 World Cup,2012,Sri Lanka,West Indies,Sri Lanka,"WI, SL, AUS, PAK",Marlon Samuels,Shane Watson
17,T20 World Cup,2014,Bangladesh,Sri Lanka,India,"SL, IND, WI, SA",K. Sangakkara,Virat Kohli
18,T20 World Cup,2016,India,West Indies,England,"WI, ENG, IND, NZ",Marlon Samuels,Virat Kohli
19,T20 World Cup,2021,UAE/Oman,Australia,New Zealand,"AUS, NZ, PAK, ENG",Mitchell Marsh,David Warner
20,T20 World Cup,2022,Australia,England,Pakistan,"ENG, PAK, IND, NZ",Sam Curran,Sam Curran
21,T20 World Cup,2024,USA/WI,India,South Africa,"IND, SA, ENG, AFG",Virat Kohli,J. Bumrah
22,Champions Trophy,1998,Bangladesh,South Africa,West Indies,"SA, WI, IND, SL",Jacques Kallis,Jacques Kallis
23,Champions Trophy,2000,Kenya,New Zealand,India,"NZ, IND, PAK, SA",Chris Cairns,-
24,Champions Trophy,2002,Sri Lanka,IND/SL Joint,-,"IND, SL, AUS, SA",-,-
25,Champions Trophy,2004,England,West Indies,England,"WI, ENG, PAK, AUS",Ian Bradshaw,R. Sarwan
26,Champions Trophy,2006,India,Australia,West Indies,"AUS, WI, NZ, SA",Shane Watson,Chris Gayle
27,Champions Trophy,2009,South Africa,Australia,New Zealand,"AUS, NZ, ENG, PAK",Shane Watson,Ricky Ponting
28,Champions Trophy,2013,UK,India,England,"IND, ENG, SL, SA",R. Jadeja,Shikhar Dhawan
29,Champions Trophy,2017,UK,Pakistan,India,"PAK, IND, ENG, BAN",Fakhar Zaman,Hasan Ali
30,Champions Trophy,2025,PAK/UAE,India,New Zealand,"IND, NZ, AUS, SA",Rohit Sharma,Rachin Ravindra
31,Champions Trophy,2026,India/sri lanka,India,New Zealand,"IND,NZ,SA,ENG",Jasprit Bumrah,Sanju samson

In [20]:
# Describe value of numeric columns describe()--function
df.describe()

              Year
count    32.000000
mean   2007.000000
std      13.389934
min    1975.000000
25%    1999.750000
50%    2009.000000
75%    2016.250000
max    2026.000000

In [21]:
# any sample ouput in sample()--function
df.sample()

,Tournament,Year,Venue,Winner,Runner-up,Semi-Finalists,Match_Winner_Final,Player_of_Tournament
18,T20 World Cup,2016,India,West Indies,England,"WI, ENG, IND, NZ",Marlon Samuels,Virat Kohli

# Step 2: Data Cleaning:

## 1.1 Initial Inspection (Before Cleaning Starts)
Method:
df.head(), df.tail(), df.sample()

df.info() → data types + nulls

df.describe() → numeric summary

df.columns → column names check

Goal: Data structure, size, आणि problems समजून घेणं.

In [23]:
# Display All Column Name in columns--function
df.columns

Index(['Tournament', 'Year', 'Venue', 'Winner', 'Runner-up', 'Semi-Finalists',
       'Match_Winner_Final', 'Player_of_Tournament'],
      dtype='object')

In [5]:
# First five rows are desplay in Head()--function
df.head()

,Tournament,Year,Venue,Winner,Runner-up,Semi-Finalists,Match_Winner_Final,Player_of_Tournament
0,ODI World Cup,1975,England,West Indies,Australia,"WI, AUS, NZ, ENG",Clive Lloyd,-
1,ODI World Cup,1979,England,West Indies,England,"WI, ENG, PAK, NZ",Viv Richards,-
2,ODI World Cup,1983,England,India,West Indies,"IND, WI, PAK, ENG",M. Amarnath,-
3,ODI World Cup,1987,India/PAK,Australia,England,"AUS, ENG, IND, PAK",David Boon,-
4,ODI World Cup,1992,AUS/NZ,Pakistan,England,"PAK, ENG, NZ, SA",Wasim Akram,Martin Crowe

In [6]:
# last five rows are display in Tail()--function
df.tail()

,Tournament,Year,Venue,Winner,Runner-up,Semi-Finalists,Match_Winner_Final,Player_of_Tournament
27,Champions Trophy,2009,South Africa,Australia,New Zealand,"AUS, NZ, ENG, PAK",Shane Watson,Ricky Ponting
28,Champions Trophy,2013,UK,India,England,"IND, ENG, SL, SA",R. Jadeja,Shikhar Dhawan
29,Champions Trophy,2017,UK,Pakistan,India,"PAK, IND, ENG, BAN",Fakhar Zaman,Hasan Ali
30,Champions Trophy,2025,PAK/UAE,India,New Zealand,"IND, NZ, AUS, SA",Rohit Sharma,Rachin Ravindra
31,Champions Trophy,2026,India/sri lanka,India,New Zealand,"IND,NZ,SA,ENG",Jasprit Bumrah,Sanju samson

In [9]:
# Which type of in the dataframes show the Info()--function
# No null value in any column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Tournament            32 non-null     object
 1   Year                  32 non-null     int64
 2   Venue                 32 non-null     object
 3   Winner                32 non-null     object
 4   Runner-up             32 non-null     object
 5   Semi-Finalists        32 non-null     object
 6   Match_Winner_Final    32 non-null     object
 7   Player_of_Tournament  32 non-null     object
dtypes: int64(1), object(7)
memory usage: 2.1+ KB

In [11]:
# Show the dtype to assign in which column in Dtypes()--function
df.dtypes

Tournament              object
Year                     int64
Venue                   object
Winner                  object
Runner-up               object
Semi-Finalists          object
Match_Winner_Final      object
Player_of_Tournament    object
dtype: object

In [13]:
# Show unique value for nuniquie()--function
df.nunique()

Tournament               3
Year                    30
Venue                   16
Winner                   9
Runner-up                9
Semi-Finalists          32
Match_Winner_Final      30
Player_of_Tournament    25
dtype: int64

In [14]:
# value of Columns and rows size --function
df.size

256

In [15]:
# row and columns Shape ()--function 
df.shape

(32, 8)

In [24]:
# Check the null percentage of data if above 70 percent data is null to check data to clearify the any serior or project  head then after action
null_percentage=df['Venue'].isnull().mean()*100
print('missing=',null_percentage)

missing= 0.0

In [26]:
# date dtype check
df['Year'].dtype

dtype('int64')

In [27]:
df['Year'].unique() # This case not any depend data in date dont change any format

array([1975, 1979, 1983, 1987, 1992, 1996, 1999, 2003, 2007, 2011, 2015,
       2019, 2023, 2009, 2010, 2012, 2014, 2016, 2021, 2022, 2024, 1998,
       2000, 2002, 2004, 2006, 2013, 2017, 2025, 2026])

In [ ]:
df.loc[df['date'] == 'March 10, 2024', 'date'] = '10-03-2024'
df.loc[df['date'] == '2024/04/05', 'date'] = '05-04-2024'
df.loc[df['date'] == '2024-01-01', 'date'] = '01-01-2024'
df['date'].unique()

In [ ]:
# check the format and change the date na fillna ()--method used
df['date']=df['date'].fillna(method='bfill')

In [ ]:
# Convert from string (object) to datetime, specifying dayfirst=True
df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y', errors='coerce')

In [ ]:
# atta apalykade ase 11 rows ahet tyanchi value 'missing' ahe tya missing la null ne replace karayache.
# nantar column la string to int karayche 
# mg null value la mean ne fill karayache
df['Column_name'] = df['Column_name'].replace('missing', np.nan)

In [ ]:
# Step 1: Convert to numeric (this will turn non-numeric like NaN or 'missing' into np.nan)
df['clicks'] = pd.to_numeric(df['clicks'], errors='coerce')
df['clicks'].dtype

## 1.2 Column Name Standardization
Rename inconsistent, messy, or duplicate column names.

In [ ]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

## 1.3 Handling Missing Values (Nulls)


Drop rows:
if condider over all dataset- जेव्हा missing rows फारच कमी असतात (जसं < 5%), तेव्हा drop करणं योग्य.

Drop specific columns
Too many nulls (> 50%)

Fill with Mean / Median / Mode
1) For Numerical Columns-use mean and median(if outliers exist)
2) For Categorical Columns- use mode

Forward Fill / Backward Fill-Time-series किंवा ordered data साठी वापरतात.

Custom Values Fill-Business knowledge वापरून specific values टाकणे.
ex- df['Age'].fillna(0, inplace=True)  # Age जर 0 असेल तर "Unknown"

Predictive Imputation (Advanced)- Missing values predict करणं using ML (Linear Regression, KNN)

In [ ]:
# df.dropna(inplace=True)  # सगळ्या rows जिथे missing आहे ते काढून टाक

### 1.4 Handling Duplicate
### 1.5 Handling Incorrect Data Types
### 1.6 Outlier Detection & Treatment
### 1.7 data formating
### 1.8 Handling Invalid or Impossible Values
### 1.9 Text Cleaning
Remove special characters, numbers, stopwords

Lowercase, lemmatize
### 1.10 correct spelling, replace, mapping
### 1.11 data normalization,scalling
### 1.12 data transformation-log, power
### 1.13 feature engineering-date feature,word count,
### 1.14 Encoding
### 1.15 data binning
### 1.16 data sampling
### 1.17 handling imbalanced data